![imagen](./img/ejercicios.png)

In [1]:
import numpy as np

## Ejercicio 1
1. Crea un array que vaya del 0 al 9 y que se llame `my_array`
2. Imprime por pantalla los elementos [9 7 5 3 1] en ese orden.

In [2]:
my_array = np.arange(10)
print(my_array)

[0 1 2 3 4 5 6 7 8 9]


In [3]:
print(my_array[::-2])

[9 7 5 3 1]


## Ejercicio 2
Imprime por pantalla la secuencia [8 7] del array `my_array`

In [4]:
print(my_array)

[0 1 2 3 4 5 6 7 8 9]


In [5]:
print(my_array[-2:-4:-1])

[8 7]


## Ejercicio 3
Imprime por pantalla la secuencia [2 1 0] de `my_array`

In [6]:
print(my_array)

[0 1 2 3 4 5 6 7 8 9]


In [7]:
print(my_array[2::-1])

[2 1 0]


In [14]:
print(np.array(sorted(my_array[:3], reverse=True)))

[2 1 0]


In [15]:
np.take(my_array, [2,1,0])

array([2, 1, 0])

## Ejercicio 4
1. Crea una matriz de 4x5, con una secuencia del 1 al 20
2. Invierte totalmente la matriz. Tanto las filas, como las columnas

In [17]:
my_matrix = np.arange(1,21).reshape(4,5)
print(my_matrix)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [18]:
print(my_matrix[::-1,::-1])

[[20 19 18 17 16]
 [15 14 13 12 11]
 [10  9  8  7  6]
 [ 5  4  3  2  1]]


In [19]:
print(np.flip(my_matrix))

[[20 19 18 17 16]
 [15 14 13 12 11]
 [10  9  8  7  6]
 [ 5  4  3  2  1]]


In [20]:
print(my_matrix.T) # Transpuesta 

[[ 1  6 11 16]
 [ 2  7 12 17]
 [ 3  8 13 18]
 [ 4  9 14 19]
 [ 5 10 15 20]]


## Ejercicio 5

Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[1, 2],
       [6, 7]])
```

In [21]:
print(my_matrix)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [34]:
print(my_matrix[:2,:2]) # matrix[start:stop:step, start:stop:step]

[[1 2]
 [6 7]]


In [55]:
lista = [[1,2,3],[4,5,6],[7,8,9]]
print(lista)
print(lista[0])
print(lista[0:1])
print(lista[0] == lista[0:1])

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
[1, 2, 3]
[[1, 2, 3]]
False


In [71]:
print(my_matrix)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [87]:
print(my_matrix[0:1,0:1])
print(my_matrix[0,0])

[[1]]
1


In [26]:
my_matrix.ndim

2

## Ejercicio 6
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[ 1,  3,  5],
       [11, 13, 15]])
```

In [88]:
print(my_matrix)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [90]:
print(my_matrix[::2,::2])

[[ 1  3  5]
 [11 13 15]]


## Ejercicio 7
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[ 5,  4,  3,  2,  1],
       [10,  9,  8,  7,  6],
       [15, 14, 13, 12, 11]])
```

In [91]:
print(my_matrix)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [92]:
print(my_matrix[:3,::-1])

[[ 5  4  3  2  1]
 [10  9  8  7  6]
 [15 14 13 12 11]]


## Ejercicio 8
Dado el siguiente array:

```Python
x = np.array(["Loro", "Perro", "Gato", "Loro", "Perro"])
```

Filtra el array para quedarte únicamente con los loros.

Resuélvelo de dos maneras diferentes

In [94]:
x = np.array(["Loro", "Perro", "Gato", "Loro", "Perro"])
print(x)

['Loro' 'Perro' 'Gato' 'Loro' 'Perro']


In [101]:
x.dtype

dtype('<U5')

In [95]:
print(x == "Loro")

[ True False False  True False]


In [96]:
print(x[x == "Loro"])

['Loro' 'Loro']


In [98]:
x[np.where(x=="Loro")]

array(['Loro', 'Loro'], dtype='<U5')

In [100]:
# np.where(x=="Loro", x, None)

## Ejercicio 9
Crea una secuencia de 20 elementos y transfórmala en un array compuesto por 2 matrices de 5x2

In [103]:
x = np.arange(20).reshape(2,5,2)
print(x)

[[[ 0  1]
  [ 2  3]
  [ 4  5]
  [ 6  7]
  [ 8  9]]

 [[10 11]
  [12 13]
  [14 15]
  [16 17]
  [18 19]]]


In [106]:
print(x.ndim)
print(x.shape)
print(x.size)

3
(2, 5, 2)
20


## Ejercicio 10

Crea un array de 10 0s. ¿Cuánto ocupa en memoria?

Sustituye el 4to elemento por 1, e imprime el array por pantalla

In [109]:
x = np.zeros(10)
print(x)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [112]:
print(x.itemsize) # bytes por elemento
print(x.nbytes) # bytes de todo el array

8
80


In [110]:
print(x.dtype)

float64


In [114]:
# 1 byte = 8 bits
8 * 8

64

In [116]:
x = np.full((10,),0)
print(x)

[0 0 0 0 0 0 0 0 0 0]


In [117]:
print(x.dtype)

int32


In [118]:
print(x.itemsize) # bytes por elemento
print(x.nbytes) # bytes de todo el array

4
40


In [140]:
np.array([-129,12], dtype=np.int8)

array([127,  12], dtype=int8)

In [ ]:
1111111

In [126]:
2**0 + 2**1 + 2**2 + 2**3 + 2**4 + 2**5 + 2**6 + 2**7

255

In [ ]:
# -128 a 127

## Ejercicio 11

Crea un vector que vaya del 10 al 49

Inviértelo

In [141]:
x = np.arange(10,50)
print(x)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [142]:
print(x[::-1])

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


## Ejercicio 12
Encuentra los índices de los valores que no sean 0 del siguiente vector [1,2,0,0,4,0]. El output sería [0, 1, 4]. [Encuentra el método apropiado en la documentación.](https://numpy.org/doc/) Encapsúlalo en una función, con un argumento de entrada de un vector.

In [144]:
ejer_12 = np.array([1,2,0,0,4,0])
print(ejer_12)

[1 2 0 0 4 0]


In [158]:
np.where(ejer_12 != 0)

(array([0, 1, 4], dtype=int64),)

In [154]:
ejer_12[np.where(ejer_12 != 0)]

array([1, 2, 4])

In [166]:
def f_ejer_12(array_1d):
    return np.where(array_1d != 0)[0]

f_ejer_12(ejer_12)

array([0, 1, 4], dtype=int64)

In [168]:
np.nonzero(ejer_12)[0]

array([0, 1, 4], dtype=int64)

## Ejercicio 13
Crea una matriz de números aleatorios 10x10. Encuentra los valores mínimo y máximo.

In [257]:
# np.random.seed(1234)
x = np.random.randint(100, size=(10,10))
print(x)
print("Mínimo", np.min(x))
print("Máximo", np.max(x))
print("Mínimo", x.min())
print("Máximo", x.max())

[[56 69 34 23 51 42 57 88 79 94]
 [66 16 28 22 27  7 18 80 87 23]
 [79  8 67 93  1 21  7 57 70 50]
 [21 13 93 13 58  8 49 47 51 17]
 [23  6 47 24  0 22 89 10 75 10]
 [ 5 68 26 99 76 80 90 68 34 63]
 [73 90 31 67 99 86  8 47 39 14]
 [ 1 13 49 24 77 50 11 84 56 35]
 [92 87 77 57  3 58 15 60 68 55]
 [ 0 58 45 59  2 56 55 36 46 67]]
Mínimo 0
Máximo 99
Mínimo 0
Máximo 99


## Ejercicio 14
Crea un vector aleatorio de tamaño 30 y calcula su media

In [258]:
x = np.random.random(30)
print(x)

[0.62467046 0.4659727  0.31697954 0.27663546 0.94824543 0.71678045
 0.25826483 0.34891066 0.47076843 0.03816733 0.29905659 0.37176556
 0.6216697  0.02697277 0.91954841 0.23886597 0.13741012 0.93742186
 0.75621919 0.95288818 0.8596591  0.86372268 0.40549722 0.69650759
 0.12349388 0.98261972 0.29340919 0.05636382 0.93454078 0.64877955]


In [260]:
print(x.sum()/len(x))

0.5197269045990385


In [262]:
print(x.mean())
print(np.mean(x))

0.5197269045990385
0.5197269045990385


In [265]:
np.average(x)

0.5197269045990385

## Ejercicio 15
Crea un array cuadrado de 2D, con las dimensiones que quieras, pero que todo el borde esté compuesto por 1s, y el interior por 0s

In [269]:
ejer_15 = np.ones((10,10))
print(ejer_15)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [272]:
ejer_15[1:-1, 1:-1] = 0
print(ejer_15)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


## Ejercicio 16
Crea una mtriz de 8x8, y rellénala con 0s y 1s. Tienes que replicar:
```Python
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
```

In [273]:
x = np.zeros((8,8))
print(x)

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


In [275]:
x[::2,1::2] = 1
print(x)
x[1::2,::2] = 1
print(x)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]
[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


## Ejercicio 17
Replica la matriz del apartado anterior, pero en este caso usando [la función `tile`](https://numpy.org/doc/stable/reference/generated/numpy.tile.html)

In [277]:
a = np.array([[0,1],
             [1,0]])

In [278]:
x = np.tile(a, (4,4))
print(x)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


## Ejercicio 18
Crea una matriz aleatoria de 5x5 y normaliza sus valores. Para normalizar tienes que restar sus valores por la media(`np.mean`) y dividir el resultado por la desviación estándar(`np.std`).

In [279]:
x = np.random.randint(1,20, (5,5))
print(x)

[[17 19  9  7  8]
 [18  1  4 14  3]
 [11 16  8  2  3]
 [ 7  5  8  8 10]
 [19  3 19  6  1]]


In [280]:
(x - np.mean(x))/ np.std(x)

array([[ 1.34860252,  1.68744738, -0.0067769 , -0.34562175, -0.17619932],
       [ 1.51802495, -1.36215631, -0.85388903,  0.84033524, -1.02331146],
       [ 0.33206796,  1.17918009, -0.17619932, -1.19273389, -1.02331146],
       [-0.34562175, -0.68446661, -0.17619932, -0.17619932,  0.16264553],
       [ 1.68744738, -1.02331146,  1.68744738, -0.51504418, -1.36215631]])

## Ejercicio 19
1. Crea una secuencia de números que vayan del 0 al 10.
2. Crea un nuevo array, que parta del anterior, pero sustituya por el valor -1, todos los elementos cuyo valor se encuentre entre el 3 y el 8.
3. Crea un nuevo array que niegue todos los elementos entre el 3 y el 8

In [281]:
x = np.arange(11)
print(x)

[ 0  1  2  3  4  5  6  7  8  9 10]


In [284]:
y = x.copy()

y[(y >= 3) & (y <= 8)] = -1
print(y)

[ 0  1  2 -1 -1 -1 -1 -1 -1  9 10]


In [285]:
z = x.copy()

z[(z >= 3) & (z <= 8)] *= -1
print(z)

[ 0  1  2 -3 -4 -5 -6 -7 -8  9 10]


In [ ]:
# i = i + 1
# i += 1

In [ ]:
# mult = mult * 2
# mult *= 2